
[font]
size = 10

[font.bold]

family = "Monofur Nerd Font"

[font.italic]
family = "Monofur Nerd Font"

[font.normal]
family = "Monofur Nerd Font"
style = "Regular"

[window]
opacity = 0.9

[window.padding]
x = 5
y = 5

[general]
import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]
