import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

[font]
size = 8

[font.bold]
family = "jetBrains Mono"

[font.italic]
family = "jetBrains Mono"

[font.normal]
family = "jetBrains Mono"
style = "Regular"

[window]
opacity = 0.9

[window.padding]
x = 5
y = 5
